docs/advanced/customizations/user-preferences.mdx
Bugfix
Fix minor spelling error
=> Fix spelling on advanced/customizations/user-prefs

docs/advanced/customizations/board-customization.mdx
>  Feature
> Added Documentation related to https://github.com/ajnart/homarr/pull/1839/
=> Added Video Backgrounds to the documentation

docs/advanced/configuration/environment-variables.mdx, docs/advanced/sso.mdx
> Bugfix / Feature
Update the documentation to reflect the changes introduced by this PR (https://github.com/ajnart/homarr/pull/2002)
https://github.com/ajnart/homarr/issues/1995
- AUTH_OIDC_TIMEOUT
=> Add support for AUTH_OIDC_TIMEOUT

docs/advanced/sso.mdx, src/css/custom.css
>Documentation
> Add reference to new env vars for https://github.com/ajnart/homarr/pull/2023 and https://github.com/ajnart/homarr/pull/2033
> Add CSS to stick lists closer to their preceding text (current spacing scheme didn't make sense)
=> feat: Add docs for new env var for auth

docs/integrations/hardware.mdx
final steps for creating the proxmox api token were slightly out of order
=> Reorder proxmox api token creation

docs/advanced/sso.mdx
> Documentation
> Add option noted in https://github.com/ajnart/homarr/issues/1994
> https://github.com/ajnart/homarr/issues/1994
=> Add AUTH_OIDC_AUTO_LOGIN

docs/integrations/hardware.mdx
=> Writing error "heath"

docs/getting-started/installation.mdx
>Documentation
> Just adding a space in the docker compose file for https://github.com/ajnart/homarr/issues/2083
> https://github.com/ajnart/homarr/issues/2083
> None
> Not a significant change
=> docs: add missing space to docker compose example.

docs/integrations/hardware.mdx
users privilege separation needs to be unchecked, won't work otherwise
Documentation
> Privilege separation needs to be unchecked.
=> docs: update hardware.mdx

docs/advanced/sso.mdx
Documentation
Clarification of which URI should be used and how
=> docs: Clarify OIDC issuer URI setup

.github/workflows/update-homarr-openapi.yaml, docs/management/api/index.mdx, package.json, pnpm-lock.yaml, src/css/custom.css
> One of: Bugfix / Feature / Code style update / Refactoring Only / Build related changes /  Documentation / Other (Please specify!)
> Briefly outline your new changes...
> Related issue: #00
> If you've added any new build scripts, environmental variables, config file options, dependency please outline here.
> If you've introduced any significant UI changes, please include a screenshot.
=> config: add open api doc

docs/getting-started/installation/helm.md, docusaurus.config.ts
=> docs(helm): add helm docs

docs/integrations/dns.mdx, docs/integrations/hardware.mdx, docs/integrations/media-server.mdx, docs/integrations/servarr.mdx, docs/integrations/torrent.mdx, docs/integrations/usenet.mdx
> One of: Bugfix / Feature / Code style update / Refactoring Only / Build related changes /  Documentation / Other (Please specify!)
> Briefly outline your new changes...
> Related issue: #00
> If you've added any new build scripts, environmental variables, config file options, dependency please outline here.
> If you've introduced any significant UI changes, please include a screenshot.
=> docs(integrations): adjust required configuration fields

docusaurus.config.ts
> One of: Bugfix / Feature / Code style update / Refactoring Only / Build related changes /  Documentation / Other (Please specify!)
> Briefly outline your new changes...
> Related issue: #00
> If you've added any new build scripts, environmental variables, config file options, dependency please outline here.
> If you've introduced any significant UI changes, please include a screenshot.
=> fix: crowdin url wrong

docs/getting-started/installation/railway.mdx
Thanks to vishify for getting it working
See  https://discord.com/channels/972958686051962910/1329852765450801193 for discord messages
=> docs(installation): add railway installation method

docs/integrations/containers.mdx
=> Added documentation for connecting to Docker Socket Proxies

docs/integrations/hardware.mdx
For OpenMediaVault, there is a plugin that must be installed. it is the openmediavault-cputemp plugin
=> docs: add note about open-media-vault cpu-temps plugin

LICENSE, docs/community/license.mdx, package.json
We should update the license of the documentation to match the main repository
Related to https://github.com/homarr-labs/homarr/pull/1684
=> chore(license): update license to apache-2 to match main repository

docs/getting-started/installation/proxmox.mdx
This PR adds Proxmox community-scripts installation method.
=> Add proxmox community-scripts

docs/advanced/single-sign-on/index.mdx
This is for https://github.com/homarr-labs/homarr/pull/2711
=> docs(auth): add force userinfo env variable for authelia v4.39

src/components/carbon.tsx, src/components/pages/home/hero/hero-cards.tsx, src/theme/TOCItems/index.tsx
I got an email from the person asking to remove styles
=> fix: carbon styling and ignore hero in argos scs

docusaurus.config.ts, src/css/custom.css
remove it until we have a working demo again that is not crashing our vps.
=> fix(header): remove demo link

docs/getting-started/installation/synology.mdx
mariushosting has since updated their tutorial for 1.32.0.
=> chore(installation): remove outdated notice for synology

docs/integrations/opnsense/index.mdx
Hi Team,
After merging [this commit](https://github.com/homarr-labs/homarr/commit/063b9a87c7e4ed03cf743b4167bd646803b8a098), the OPNsense and Firewall widget documentation must be updated to include the following:
**Create a Dedicated User for Integration**
A new, exclusive user should be created in OPNsense solely for this integration to ensure security and isolation.
**Apply the Principle of Least Privilege**
Assign only the required privileges to this user:
Lobby: Dashboard
Reporting: Traffic
**Generate and Secure API Credentials**
Provide clear instructions on how to:
Generate the API Key and API Secret.
Download and securely store these credentials (they will only be displayed once).
=> docs:(integration) Update opnsense and firewall widget

docs/advanced/environment-variables/index.mdx
Only merge once the implementation is merged on main repo https://github.com/homarr-labs/homarr/pull/3915
=> docs(env): improve support for instances without internet connection
